# Generated by Django 3.0.5 on 2020-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cpp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='patent_valid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='pii',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='strength1_avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='strength2_avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='strength3_avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='strength4_avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='strength5_avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='ts',
            field=models.FloatField(),
        ),
    ]
