# Generated by Django 3.0.5 on 2020-06-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_patentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentdetail',
            name='patentnumber',
            field=models.CharField(max_length=200),
        ),
    ]
